'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Your_Style.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Classic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Classic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicAquaBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicAquaBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicAquaEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicAquaEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicAquaHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicAquaHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicAquaLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicAquaLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicAquaQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicAquaQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicAquaVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicAquaVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlackBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlackBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlackEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlackEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlackHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlackHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlackLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlackLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlackQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlackQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlackVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlackVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlueBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlueBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlueEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlueEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlueHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlueHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlueLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlueLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlueQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlueQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicBlueVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicBlueVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGrayBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGrayBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGrayEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGrayEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGrayHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGrayHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGrayLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGrayLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGrayQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGrayQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGrayVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGrayVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGreenBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGreenBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGreenEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGreenEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGreenHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGreenHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGreenLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGreenLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGreenQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGreenQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicGreenVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicGreenVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicLimeBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicLimeBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicLimeEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicLimeEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicLimeHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicLimeHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicLimeLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicLimeLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicLimeQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicLimeQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicLimeVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicLimeVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicPinkBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicPinkBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicPinkEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicPinkEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicPinkHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicPinkHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicPinkLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicPinkLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicPinkQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicPinkQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicPinkVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicPinkVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicRedBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicRedBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicRedEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicRedEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicRedHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicRedHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicRedLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicRedLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicRedQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicRedQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicRedVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicRedVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicWhiteBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicWhiteBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicWhiteEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicWhiteEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicWhiteHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicWhiteHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicWhiteLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicWhiteLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicWhiteQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicWhiteQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClassicWhiteVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassicWhiteVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Retro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Retro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroAquaBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroAquaBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroAquaEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroAquaEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroAquaHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroAquaHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroAquaLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroAquaLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroAquaQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroAquaQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroAquaVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroAquaVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBacking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBacking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlackBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlackBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlackEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlackEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlackHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlackHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlackLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlackLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlackQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlackQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlackVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlackVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlueBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlueBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlueEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlueEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlueHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlueHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlueLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlueLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlueQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlueQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroBlueVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroBlueVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGrayBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGrayBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGrayEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGrayEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGrayHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGrayHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGrayLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGrayLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGrayQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGrayQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGrayVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGrayVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGreenBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGreenBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGreenEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGreenEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGreenHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGreenHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGreenLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGreenLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGreenQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGreenQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroGreenVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroGreenVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroLimeBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroLimeBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroLimeEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroLimeEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroLimeHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroLimeHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroLimeLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroLimeLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroLimeQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroLimeQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroLimeVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroLimeVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroPinkBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroPinkBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroPinkEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroPinkEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroPinkHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroPinkHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroPinkLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroPinkLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroPinkQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroPinkQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroPinkVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroPinkVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroRedBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroRedBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroRedEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroRedEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroRedHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroRedHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroRedLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroRedLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroRedQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroRedQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroRedVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroRedVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroWhiteBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroWhiteBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroWhiteEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroWhiteEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroWhiteHeelTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroWhiteHeelTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroWhiteLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroWhiteLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroWhiteQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroWhiteQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RetroWhiteVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RetroWhiteVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vintage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vintage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageAquaBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageAquaBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageAquaEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageAquaEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageAquaLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageAquaLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageAquaQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageAquaQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageAquaVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageAquaVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBacking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBacking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlackBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlackBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlackEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlackEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlackLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlackLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlackQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlackQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlackVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlackVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlueBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlueBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlueEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlueEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlueLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlueLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlueQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlueQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageBlueVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageBlueVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGrayBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGrayBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGrayEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGrayEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGrayLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGrayLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGrayQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGrayQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGrayVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGrayVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGreenBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGreenBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGreenEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGreenEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGreenLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGreenLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGreenQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGreenQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageGreenVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageGreenVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageLimeBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageLimeBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageLimeEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageLimeEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageLimeLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageLimeLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageLimeQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageLimeQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageLimeVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageLimeVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintagePinkBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintagePinkBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintagePinkEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintagePinkEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintagePinkLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintagePinkLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintagePinkQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintagePinkQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintagePinkVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintagePinkVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageRedBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageRedBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageRedEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageRedEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageRedLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageRedLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageRedQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageRedQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageRedVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageRedVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageWhiteBackCounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageWhiteBackCounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageWhiteEyestay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageWhiteEyestay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageWhiteLaces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageWhiteLaces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageWhiteQuarter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageWhiteQuarter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VintageWhiteVamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VintageWhiteVamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
